### ISSUE TITLE
Provide "changes" API endpoint

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow-api#200]
- [x] Auth
- [ ] Auth Perf
- [x] Deploy
- [x] Datapoint changes/deletes
- [x] "Long pull"
- [x] Change Flow to push Form.status
- [x] Survey data

**Comment by iperdomo** [comment]
> "Long pull"

I'm thinking on caching the `HTTP 204` request instead of blocking a thread in nginx or the JVM.

It's an _easier_ solution. We can return `Cache-Control: max-age=3600` (1h) header from Clojure and nginx will honor it (if `proxy_cache` is enabled)

@dlebrero any thoughts?

References:
* https://www.nginx.com/blog/nginx-caching-guide/
* https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache
* https://serverfault.com/questions/822771/nginx-lua-set-cache-key-based-on-upstream-response-headers

**Comment by dlebrero** [comment]
> > "Long pull"
> 
> I'm thinking on caching the `HTTP 204` request instead of blocking a thread in nginx or the JVM.
> 
> It's an _easier_ solution. We can return `Cache-Control: max-age=3600` (1h) header from Clojure and nginx will honor it (if `proxy_cache` is enabled)
> 
> @dlebrero any thoughts?

Seems reasonable and a lot simpler. I assume the cache key will be the user email + url?

**Comment by iperdomo** [comment]
>Seems reasonable and a lot simpler. I assume the cache key will be the user email + url?

yes, email+request_uri

**Comment by dlebrero** [comment]
Can we close this?
