### ISSUE TITLE
URL restructuring

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow-api#94]
We have discussed possibly redesigning some of the http endpoints.

The current endpoints are the following:

```
https://api.akvo.org/flow/orgs/<org>/folders?parentId=<parent-id>
https://api.akvo.org/flow/orgs/<org>/surveys?folderId=<folder-id>
https://api.akvo.org/flow/orgs/<org>/survey/<survey-id>
https://api.akvo.org/flow/orgs/<org>/data-points/<survey-id>
https://api.akvo.org/flow/orgs/<org>/form-instances/<survey-id>/<form-id>
```

I could imagine the last two instead being

```
https://api.akvo.org/flow/orgs/<org>/survey/<survey-id>/data-points
https://api.akvo.org/flow/orgs/<org>/survey/<survey-id>/form/<form-id>/form-instances
```

As the `survey` and `form` in the path is in singular, I wonder if we should also change `orgs` to `org`, or perhaps the other way around, change `survey` and `form` to `surveys` and `forms`?

**Comment by iperdomo** [comment]
I propose to change to plural version of the paths: `surveys` and `forms`

**Comment by jonase** [comment]
The current proposal is

```
https://api.akvo.org/flow/orgs/<org>/folders?parentId=<parent-id>
https://api.akvo.org/flow/orgs/<org>/surveys?folderId=<folder-id>
https://api.akvo.org/flow/orgs/<org>/surveys/<survey-id>
https://api.akvo.org/flow/orgs/<org>/surveys/<survey-id>/data-points
https://api.akvo.org/flow/orgs/<org>/surveys/<survey-id>/forms/<form-id>/form-instances
```

**Comment by muloem** [comment]
I am leaning more towards using query parameters.  As you say its about identifying resources so when I think of the resources returned for each request they seem more fitting to use query parameters. e.g. 

    https://api.akvo.org/flow/orgs/<org>/surveys/<survey-id>

Returns the survey with `surveys` as the element in the object.

So I would think since `datapoints` are the top level element returned, then the URI should reflect that as well. ~Same for form instances.~  URI example included..

    https://api.akvo.org/flow/orgs/<org>/data-points?surveyId=<survey-id>

**Comment by muloem** [comment]
When I think further for form instances thats a bit more complex because in our current setup, form instances are part of a datapoint.  So perhaps in this case its more appropriate to have something like 

    https://api.akvo.org/flow/orgs/<org>/data-points/<datapoint-id>/form-instances
    https://api.akvo.org/flow/orgs/<org>/data-points/<datapoint-id>/form-instances?formId=<form-id>


In order, however, to maintain the previous situations where we were querying by form instances as well, we could support 

    https://api.akvo.org/flow/orgs/<org>/form-instances?formId=<form-id>

**Comment by muloem** [comment]
So for the last two URIs I would propose

    https://api.akvo.org/flow/orgs/<org>/data-points
    https://api.akvo.org/flow/orgs/<org>/form-instances

And then the filtering can be added. e.g by `surveyId` for datapoints and by `formId` for form instances

**Comment by jonase** [comment]
Latest proposal:

```
https://api.akvo.org/flow/orgs/<org>/folders?parent_id=<parent_id>
https://api.akvo.org/flow/orgs/<org>/surveys?folder_id=<folder_id>
https://api.akvo.org/flow/orgs/<org>/surveys/<survey_id>
https://api.akvo.org/flow/orgs/<org>/data_points?survey_id=<survey-id>
https://api.akvo.org/flow/orgs/<org>/form_instances?survey_id=<survey_id>&form_id=<form_id>
```
